### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy

### ISSUE THREAD

**Issue by Kinzeng** [big-data-europe/docker-spark#62]
Hi, I'm getting an error when I submit a spark application from a `bde2020/spark-submit:2.4.0-hadoop2.7` container to the `bde2020/spark-submit:2.4.0-hadoop2.7` container:

```
[task-result-getter-0] WARN org.apache.spark.scheduler.TaskSetManager - Lost task 0.0 in stage 0.0 (TID 0, 172.18.0.12, executor 0): java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-791b98df-469b-42a9-922e-5cf3481bc613-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.7-791b98df-469b-42a9-922e-5cf3481bc613-libsnappyjava.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
	at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
	at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
	at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
	at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at org.apache.kafka.common.utils.ByteUtils.readVarint(ByteUtils.java:168)
	at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:292)
	at org.apache.kafka.common.record.DefaultRecordBatch$1.readNext(DefaultRecordBatch.java:264)
	at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:563)
	at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:532)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.nextFetchedRecord(Fetcher.java:1146)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1181)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1500(Fetcher.java:1035)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:544)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:505)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1259)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1187)
...
```

I'm submitting the application using this command from the `spark-submit` container:
```
/spark/bin/spark-submit \
  --class "Main" \
  --master spark://spark-master:7077 \
  --deploy-mode client \
  --driver-class-path /app/pipeline/target/scala-2.11/streaming.jar \
  /app/pipeline/target/scala-2.11/streaming.jar
```

I didn't have this problem a month ago when I upgraded to spark 2.4.0, but after rebuilding the images last week I haven't been able to submit the application. Any ideas about what I might be doing wrong? 

Thanks for your time,
Kinzeng

**Comment by Kinzeng** [comment]
Here is how I defined the docker services:
```
  spark-master:
    env_file: ./.env.development
    image: bde2020/spark-master:2.4.0-hadoop2.7
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - ENABLE_INIT_DAEMON=false
      - "constraint:node==master"
    volumes:
      - ./processor:/app
    networks:
      - dev

  spark-worker:
    env_file: ./.env.development
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MASTER=spark://spark-master:7077
      - "constraint:node==master"
    networks:
      - dev

  spark-submit:
    env_file: ./.env.development
    image: bde2020/spark-submit:2.4.0-hadoop2.7
    volumes:
      - ./:/app
    networks:
      - dev
```

**Comment by GezimSejdiu** [comment]
Hi @Kinzeng ,
many thanks for the issue. 
This is strange, did you check if this classpath is already bundled on `streaming.jar`? If not, than we may miss something here when we [moved to `alpine` instead of `debian`](https://github.com/big-data-europe/docker-spark/pull/52).

Please, could you double check and let us know. 

Best regards,

**Comment by Kinzeng** [comment]
Hey @GezimSejdiu,
So while I was testing out different configurations for my streaming app, I tried adding Snappy in `build.sbt` before building the jar with `sbt assembly`, but still got the same result.

I did some research and found that most people running into this issue simply had to install `libc6-compat` on the machines to fix the issue. Here are some reference links:
https://github.com/wurstmeister/kafka-docker/issues/435
https://github.com/grpc/grpc/issues/6126

The issues here are not specifically about spark, but it seems like they are running into the same error message.

I also consulted a devops coworker (who deployed a kafka cluster for our infrastructure a while ago) and he mentioned that Snappy needs to be installed both on the image and in the jar's classpath to work. He mentioned a `libsnappy-dev` package that he installed on the ubuntu machine. I searched around and found some [snappy libraries for alpine](https://pkgs.alpinelinux.org/contents?file=&path=&name=snappy-dev&branch=edge&repo=main&arch=armhf).

I think we should try installing `libc6-compat` first since it seems others have solved it like this. I'm not super experienced with docker so I'm not sure exactly how to go about installing these on the spark images myself.

**Comment by Kinzeng** [comment]
So in the end I created a custom image based off of your images and installed the `libc6-compat` package separately for both master and worker:
```
FROM bde2020/spark-master:2.4.0-hadoop2.7

RUN apk update && apk add --no-cache libc6-compat
```

I realize that not everyone will need this package installed, so i'll leave it up to you to decide whether or not this should be installed by default. Thanks for the help!

**Comment by GezimSejdiu** [comment]
Hi @Kinzeng ,
great! Many thanks for your detailed information. Give me some time to think and see if we can include this on the base image (if it does not affect the size of the image) and will let you know.

The way you did looks good and maybe we could document it somewhere if someone else faces the same issue. 
Will come back to you as soon as I find more time to look into it.

Best regards,

**Comment by AceHack** [comment]
I'm having the same issue with an image I created from https://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images using v2.4.3 ./bin/docker-image-tool.sh.  libc6-compat did not fix it for me, any ideas?  Thanks.

**Comment by gmouchakis** [comment]
@AceHack you could try https://github.com/big-data-europe/docker-spark/pull/79.

**Comment by AceHack** [comment]
I did https://github.com/big-data-europe/docker-spark/commit/e96a216c06165a11231de76afa225fd0c54da01e myself to fix the issue.  Thanks for the help.

**Comment by vijaysarangapani** [comment]
Am facing below issue, could you some body help and am trying in docker container of my application
and i tried /tmp 777 permissions and  -Dorg.xerial.snappy.use.systemlib=true -Dorg.xerial.snappy.lib.path=/usr/lib/libsnappyjava.so all possibilities 

java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure. UnsafeUtil 
 at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressed Length (SnappyRawCompressor.java:405) 
 at org.xerial.snappy.pure.SnappyRawCompressor.compress (SnappyRawCompressor.java:111) 
 at org.xerial.snappy.pure. PureJavaSnappy.rawCompress (PureJavaSnappy.java:128) 
 at org.xerial.snappy.Snappy.rawCompress (Snappy.java:450) at org.xerial.snappy. Snappy.compress (Snappy.java:123) 
 at org.xerial.snappy. SnappyOutputStream.compress Input (SnappyOutputStream.java:380) 
 at org.xerial.snappy. SnappyOutputStream.flush(SnappyOutputStream.java:334) 
 at org.xerial. snappy. SnappyOutputStream.close(SnappyOutputStream.java:419) 
 at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:191) 
 at org.apache.kafka.common.record. MemoryRecordsBuilder.closeForRecordAppends (MemoryRecordsBuilder.java:314) 
 at org.apache.kafka.common.record.MemoryRecordsBuilder.close(MemoryRecordsBuilder.java:349) 
 at org.apache.kafka.clients.producer.internals. ProducerBatch.close(ProducerBatch.java:453) 
 at org.apache.kafka.clients.producer.internals. RecordAccumulator.drainBatchesForOneNode(RecordAccumulator.java:609) 
 at org.apache.kafka.clients.producer.internals. RecordAccumulator.drain (RecordAccumulator.java:636) 
 at org.apache.kafka.clients.producer.internals.Sender.sendProducerData (Sender.java:361) 
 at org.apache.kafka.clients.producer.internals.Sender.runOnce (Sender.java:327) 
 at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) 
 at java.base/java.lang.Thread.run(Thread.java:831) 
 Suppressed: org.xerial.snappy.SnappyError: [UNSUPPORTED PLATFORM] pure-java snappy requires access to java.nio.Buffer raw address field 
 at org.xerial.snappy.pure. UnsafeUtil.<clinit>(UnsafeUtil.java:49) 
 at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressed Length (SnappyRawCompressor.java:405) 
 at org.xerial.snappy.pure. SnappyRawCompressor.compress (SnappyRawCompressor.java:111) 
 at org.xerial.snappy.pure.PureJavaSnappy.rawCompress (PureJavaSnappy.java:128) 
 at org.xerial.snappy. Snappy.rawCompress (Snappy.java:450) at org.xerial.snappy. Snappy.compress (Snappy.java:123) 
 at org.xerial.snappy. SnappyOutputStream.compress Input (SnappyOutputStream.java:380) 
 at org.xerial.snappy. SnappyOutputStream.flush(SnappyOutputStream.java:334) 
 at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:128) 
 at java.base/java.io.FilterOutputstream.close(FilterOutputStream.java:182)

**Comment by vijaysarangapani** [comment]
> Am facing below issue, could you some body help and am trying in docker container of my application and i tried /tmp 777 permissions and -Dorg.xerial.snappy.use.systemlib=true -Dorg.xerial.snappy.lib.path=/usr/lib/libsnappyjava.so all possibilities
> 
> java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure. UnsafeUtil at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressed Length (SnappyRawCompressor.java:405) at org.xerial.snappy.pure.SnappyRawCompressor.compress (SnappyRawCompressor.java:111) at org.xerial.snappy.pure. PureJavaSnappy.rawCompress (PureJavaSnappy.java:128) at org.xerial.snappy.Snappy.rawCompress (Snappy.java:450) at org.xerial.snappy. Snappy.compress (Snappy.java:123) at org.xerial.snappy. SnappyOutputStream.compress Input (SnappyOutputStream.java:380) at org.xerial.snappy. SnappyOutputStream.flush(SnappyOutputStream.java:334) at org.xerial. snappy. SnappyOutputStream.close(SnappyOutputStream.java:419) at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:191) at org.apache.kafka.common.record. MemoryRecordsBuilder.closeForRecordAppends (MemoryRecordsBuilder.java:314) at org.apache.kafka.common.record.MemoryRecordsBuilder.close(MemoryRecordsBuilder.java:349) at org.apache.kafka.clients.producer.internals. ProducerBatch.close(ProducerBatch.java:453) at org.apache.kafka.clients.producer.internals. RecordAccumulator.drainBatchesForOneNode(RecordAccumulator.java:609) at org.apache.kafka.clients.producer.internals. RecordAccumulator.drain (RecordAccumulator.java:636) at org.apache.kafka.clients.producer.internals.Sender.sendProducerData (Sender.java:361) at org.apache.kafka.clients.producer.internals.Sender.runOnce (Sender.java:327) at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) at java.base/java.lang.Thread.run(Thread.java:831) Suppressed: org.xerial.snappy.SnappyError: [UNSUPPORTED PLATFORM] pure-java snappy requires access to java.nio.Buffer raw address field at org.xerial.snappy.pure. UnsafeUtil.(UnsafeUtil.java:49) at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressed Length (SnappyRawCompressor.java:405) at org.xerial.snappy.pure. SnappyRawCompressor.compress (SnappyRawCompressor.java:111) at org.xerial.snappy.pure.PureJavaSnappy.rawCompress (PureJavaSnappy.java:128) at org.xerial.snappy. Snappy.rawCompress (Snappy.java:450) at org.xerial.snappy. Snappy.compress (Snappy.java:123) at org.xerial.snappy. SnappyOutputStream.compress Input (SnappyOutputStream.java:380) at org.xerial.snappy. SnappyOutputStream.flush(SnappyOutputStream.java:334) at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:128) at java.base/java.io.FilterOutputstream.close(FilterOutputStream.java:182)

and my jar is working as java -jar but it is not working in container
