### ISSUE TITLE
Exception when submitting to spark 2.2.2

### ISSUE THREAD

**Issue by konradmalik** [big-data-europe/docker-spark#64]
Hi,
I think there may be some versions mismatch for 2.2.2-hadoop2.7 version of your submit container.
When I run my app on 2.2.2-hadoop2.7 cluster I have exception (most probably versions mismatch):
```
19/03/07 15:43:06 ERROR TransportRequestHandler: Error while invoking RpcHandler#receive() on RPC id 6892155609033431893
java.io.InvalidClassException: org.apache.spark.storage.BlockManagerId; local class incompatible: stream classdesc serialVersionUID = -3720498261147521051, local class serialVersionUID = 6155820641931972169
    at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
```

When I looked inside a running spark-submit 2.2.2-hadoop2.7 container I noticed that spark version is actually different:
Spark 2.2.1 built for Hadoop 2.7.3

May this be the cause of this issue? Any idea how can I make it to run properly?

My pom looks ok, should not give any incompatibilities:
```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <java.version>1.8</java.version>
        <scala.version>2.11.12</scala.version>
        <spark-version>2.2.2</spark-version>
        <spark-cassandra-connector.version>2.0.11</spark-cassandra-connector.version>
        <paho.client.version>1.2.1</paho.client.version>

    </properties>

    <dependencies>
        <!-- scala-maven-plugin determines the Scala version to use from this dependency -->
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.spark/spark-core -->
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>${spark-version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.spark/spark-sql -->
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.11</artifactId>
            <version>${spark-version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.spark/spark-mllib -->
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_2.11</artifactId>
            <version>${spark-version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.datastax.spark/spark-cassandra-connector -->
        <dependency>
            <groupId>com.datastax.spark</groupId>
            <artifactId>spark-cassandra-connector_2.11</artifactId>
            <version>${spark-cassandra-connector.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_2.11</artifactId>
            <version>${spark-version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming-kafka-0-10_2.11</artifactId>
            <version>${spark-version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>${paho.client.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.bahir</groupId>
            <artifactId>spark-streaming-mqtt_2.11</artifactId>
            <version>${spark-version}</version>
        </dependency>



    </dependencies>
```

EDIT:
Yup, changing all versions to 2.2.1 allowed me to run my app, nevertheless the spark-submit 2.2.2-hadoop2.7 container needs to be fixed as it contains wrong spark version.

**Comment by GezimSejdiu** [comment]
Hi @konradmalik ,

many thanks for the detailed issue. This is due to the dependencies images (spark-master depend on the spark-base image) and therefore docker.hub wasn't able to wait until the base image was built. Will trigger the builds once more and hopefully, the issue will be resolved. 

Will comment when they are done so you could check if this issue still persists.

Best regards,

**Comment by konradmalik** [comment]
@GezimSejdiu, Just asking - any progress on this?

**Comment by GezimSejdiu** [comment]
Hi @konradmalik ,

I have tried to trigger a build at docker.hub but due to some changes there (on the new version of the interface) that wasn't possible or I wasn't able to create a manual build :(. In order to trigger the build from the repo, I just created [an empty commit](https://github.com/big-data-europe/docker-spark/commit/8c5c3dfef1b344c039f08d5b96861e543bf135d4) with the hope that the build (on docker.hub) will trigger the changes and build the image as it is supposed to.

If this will not work out, the only option is that you use the latest versions of Spark until we find a solution for that.

Best regards

**Comment by konradmalik** [comment]
Hi,
sorry for it taking so long but the error is still there :(
The same exception is thrown.
